### ISSUE TITLE
Need to push a new package?

### ISSUE THREAD

**Issue by bnewbold** [xobs/pulseaudio-novena#1]
As far as I can tell the recent changes (in November 2014) are quite helpful, but have not been pushed to the kosagi debian repo in the form of a 1.1 or later .deb.

The audio on my headless board did not work by default with most recent pulseaudio-novena from the repos (v1.0-1 IIRC), but does work fine (once volume is turned up with alsamixer) with a self-built version of this package from master.

**Comment by xobs** [comment]
A new version was pushed today.
